version: 2.0.0.{build}
image: Visual Studio 2019


environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    PlatformToolset: v142
  
platform:
    - x64
    - x86

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x86

    - if "%platform%"=="x86" set archi=x86
    - if "%platform%"=="x86" set platform_input=x86

    - if "%PlatformToolset%"=="v142" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild NppNavigateTo.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\Release-x64\NavigateTo.dll" -FileName NavigateTo.dll
        }

        if ($env:PLATFORM -eq "x86" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\Release\NavigateTo.dll" -FileName NavigateTo.dll
        }
        
        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release") {
            if($env:PLATFORM -eq "x64"){
            $ZipFileName = "NavigateTo_$($env:APPVEYOR_REPO_TAG_NAME)_$($env:PLATFORMTOOLSET)_x64.zip"
            7z a $ZipFileName .\bin\Release-x64\*
            } else {
            $ZipFileName = "NavigateTo_$($env:APPVEYOR_REPO_TAG_NAME)_$($env:PLATFORMTOOLSET)_x86.zip"
            7z a $ZipFileName .\bin\Release\*
            }
        }

artifacts:
  - path: NavigateTo_*.zip
    name: releases